// [character, pinyin, meanings]
// Roughly frequency-ordered (news + everyday usage blend).
export const CHARS = [
  ["的","de","possessive particle; of"],
  ["一","yī","one"],
  ["是","shì","to be; yes"],
  ["不","bù","not, no"],
  ["了","le / liǎo","completed-action particle; to finish"],
  ["在","zài","at, in; to exist"],
  ["人","rén","person, people"],
  ["有","yǒu","to have; there is"],
  ["我","wǒ","I, me"],
  ["他","tā","he, him"],
  ["这","zhè","this"],
  ["中","zhōng","middle, center; China"],
  ["大","dà","big, great"],
  ["来","lái","to come"],
  ["上","shàng","up, above; to go up"],
  ["国","guó","country, nation"],
  ["个","gè","general measure word"],
  ["到","dào","to arrive; up to"],
  ["说","shuō","to speak, say"],
  ["们","men","plural marker (we, they)"],
  ["为","wèi / wéi","for; to act as"],
  ["子","zǐ","child, son; noun suffix"],
  ["和","hé","and; harmony"],
  ["你","nǐ","you"],
  ["地","dì / de","earth, ground; adverb particle"],
  ["出","chū","to go out, exit"],
  ["道","dào","road, way; Dao; to say"],
  ["也","yě","also, too"],
  ["时","shí","time; hour"],
  ["年","nián","year"],
  ["得","dé / de / děi","to get; particle; must"],
  ["就","jiù","then, right away; just"],
  ["那","nà","that"],
  ["要","yào","to want; will; important"],
  ["下","xià","down, below; to descend"],
  ["以","yǐ","by means of; according to"],
  ["生","shēng","to be born; life; raw"],
  ["会","huì","can; will; meeting"],
  ["自","zì","self; from"],
  ["着","zhe / zháo","ongoing-action particle; to touch"],
  ["去","qù","to go"],
  ["之","zhī","of (classical); it"],
  ["过","guò","to pass; past-experience marker"],
  ["家","jiā","home, family"],
  ["学","xué","to study, learn"],
  ["对","duì","correct; toward; pair"],
  ["可","kě","can, may; -able"],
  ["她","tā","she, her"],
  ["里","lǐ","inside; neighborhood"],
  ["后","hòu","after, behind"],
  ["小","xiǎo","small, little"],
  ["么","me","suffix: 什么 = what"],
  ["心","xīn","heart, mind"],
  ["多","duō","many, much; how"],
  ["天","tiān","sky, day, heaven"],
  ["而","ér","and, but, yet"],
  ["能","néng","can, able; energy"],
  ["好","hǎo / hào","good; to like"],
  ["都","dōu / dū","all; capital city"],
  ["然","rán","so, thus: 然后 = then"],
  ["没","méi / mò","not have; to sink"],
  ["日","rì","sun, day"],
  ["于","yú","at, in, to (formal)"],
  ["起","qǐ","to rise, get up, start"],
  ["还","hái / huán","still, also; to return"],
  ["发","fā / fà","to send out, develop; hair"],
  ["成","chéng","to become; succeed"],
  ["事","shì","matter, affair, thing"],
  ["只","zhǐ / zhī","only; measure word for animals"],
  ["作","zuò","to do, make; work"],
  ["当","dāng / dàng","when; to serve as"],
  ["想","xiǎng","to think, want, miss"],
  ["看","kàn","to look, watch, read"],
  ["文","wén","writing, language, culture"],
  ["无","wú","without, none"],
  ["开","kāi","to open; start; drive"],
  ["手","shǒu","hand"],
  ["十","shí","ten"],
  ["用","yòng","to use"],
  ["主","zhǔ","main; master, owner"],
  ["行","xíng / háng","to walk; OK; row; profession"],
  ["方","fāng","square; direction; method"],
  ["又","yòu","again; both...and"],
  ["如","rú","like, as; if"],
  ["前","qián","front, before"],
  ["所","suǒ","place; that which"],
  ["本","běn","root, origin; measure word for books"],
  ["见","jiàn","to see, meet"],
  ["经","jīng","to pass through; classic: 已经 = already"],
  ["头","tóu","head; top"],
  ["面","miàn","face, surface; noodles"],
  ["公","gōng","public; male; fair"],
  ["同","tóng","same, together"],
  ["三","sān","three"],
  ["已","yǐ","already"],
  ["老","lǎo","old; venerable"],
  ["从","cóng","from; to follow"],
  ["动","dòng","to move; action"],
  ["两","liǎng","two (of something)"],
  ["长","cháng / zhǎng","long; to grow; chief"],
  ["知","zhī","to know"],
  ["民","mín","people, citizens"],
  ["样","yàng","appearance, kind: 这样 = this way"],
  ["现","xiàn","present, now; to appear"],
  ["分","fēn / fèn","to divide; minute; point"],
  ["将","jiāng / jiàng","will (future); general (military)"],
  ["外","wài","outside, foreign"],
  ["但","dàn","but, however"],
  ["身","shēn","body; oneself"],
  ["些","xiē","some, a few"],
  ["与","yǔ","and, with (formal)"],
  ["高","gāo","tall, high"],
  ["意","yì","meaning, idea, intention"],
  ["进","jìn","to enter, advance"],
  ["把","bǎ","to hold; object marker"],
  ["法","fǎ","law; method; France"],
  ["此","cǐ","this (formal)"],
  ["实","shí","real, true; solid"],
  ["回","huí","to return; measure word for times"],
  ["二","èr","two"],
  ["理","lǐ","reason, logic; to manage"],
  ["美","měi","beautiful; America"],
  ["点","diǎn","point, dot; o'clock; a little"],
  ["月","yuè","moon, month"],
  ["明","míng","bright; clear; next (day/year)"],
  ["其","qí","its, his, their (formal)"],
  ["种","zhǒng / zhòng","kind, type; seed; to plant"],
  ["声","shēng","sound, voice"],
  ["全","quán","whole, all, complete"],
  ["工","gōng","work, worker; industry"],
  ["己","jǐ","self: 自己 = oneself"],
  ["话","huà","speech, words"],
  ["儿","ér","child, son; -r suffix"],
  ["者","zhě","one who... (-er)"],
  ["向","xiàng","toward; direction"],
  ["情","qíng","feeling, emotion; situation"],
  ["部","bù","part, section; ministry"],
  ["正","zhèng","correct, upright; just now"],
  ["名","míng","name; famous"],
  ["定","dìng","to fix, decide; certainly"],
  ["女","nǚ","woman, female; daughter"],
  ["问","wèn","to ask"],
  ["力","lì","power, strength"],
  ["机","jī","machine; opportunity"],
  ["给","gěi","to give; for"],
  ["等","děng","to wait; rank; etc."],
  ["几","jǐ / jī","how many; a few"],
  ["很","hěn","very"],
  ["业","yè","trade, industry; occupation"],
  ["最","zuì","most, -est"],
  ["间","jiān / jiàn","between; room; gap"],
  ["新","xīn","new"],
  ["什","shén","what: 什么"],
  ["打","dǎ","to hit; to play, do"],
  ["便","biàn / pián","convenient; then; 便宜 = cheap"],
  ["位","wèi","position; measure word for people (polite)"],
  ["因","yīn","because; cause"],
  ["重","zhòng / chóng","heavy; important; to repeat"],
  ["被","bèi","passive marker (by); quilt"],
  ["走","zǒu","to walk, go, leave"],
  ["电","diàn","electricity"],
  ["四","sì","four"],
  ["第","dì","ordinal prefix: 第一 = first"],
  ["门","mén","door, gate"],
  ["相","xiāng / xiàng","mutual; appearance, photo"],
  ["次","cì","time (occurrence); order"],
  ["东","dōng","east"],
  ["政","zhèng","politics, government"],
  ["海","hǎi","sea, ocean"],
  ["口","kǒu","mouth; opening"],
  ["使","shǐ","to make, cause; envoy"],
  ["教","jiāo / jiào","to teach; religion"],
  ["西","xī","west"],
  ["再","zài","again; further"],
  ["平","píng","flat, level; peaceful"],
  ["真","zhēn","true, real; really"],
  ["听","tīng","to listen"],
  ["世","shì","world; generation"],
  ["气","qì","air, gas; breath; anger"],
  ["信","xìn","letter; to believe; trust"],
  ["北","běi","north"],
  ["少","shǎo / shào","few, little; young"],
  ["关","guān","to close; pass; 关系 = relation"],
  ["并","bìng","and, moreover; to combine"],
  ["内","nèi","inside, inner"],
  ["加","jiā","to add; plus"],
  ["化","huà","to transform; -ization"],
  ["由","yóu","from, by; reason"],
  ["却","què","however, yet"],
  ["代","dài","generation; era; to replace"],
  ["军","jūn","army, military"],
  ["产","chǎn","to produce; product, property"],
  ["入","rù","to enter"],
  ["先","xiān","first, before; Mr. (先生)"],
  ["山","shān","mountain"],
  ["五","wǔ","five"],
  ["太","tài","too (excessively); great"],
  ["水","shuǐ","water"],
  ["万","wàn","ten thousand"],
  ["市","shì","city; market"],
  ["眼","yǎn","eye"],
  ["体","tǐ","body; form, style"],
  ["别","bié","don't; other; to part"],
  ["处","chù / chǔ","place; to handle"],
  ["总","zǒng","always; total; chief"],
  ["才","cái","only then; talent"],
  ["场","chǎng","field, site; measure word for events"],
  ["师","shī","teacher, master"],
  ["书","shū","book; to write"],
  ["比","bǐ","to compare; than; ratio"],
  ["住","zhù","to live (reside); to stop"],
  ["员","yuán","member, personnel"],
  ["九","jiǔ","nine"],
  ["笑","xiào","to laugh, smile"],
  ["性","xìng","nature, character; gender; -ness"],
  ["通","tōng","to go through, connect"],
  ["目","mù","eye (formal); item, goal"],
  ["华","huá","splendid; China"],
  ["报","bào","to report; newspaper"],
  ["立","lì","to stand; establish"],
  ["马","mǎ","horse"],
  ["命","mìng","life; fate; order"],
  ["张","zhāng","measure word for flat things; to stretch"],
  ["活","huó","to live; alive; work"],
  ["难","nán / nàn","difficult; disaster"],
  ["神","shén","god, spirit; amazing"],
  ["数","shù / shǔ","number; to count"],
  ["件","jiàn","measure word for items; item"],
  ["安","ān","peace, safe; to install"],
  ["表","biǎo","surface; to express; form; watch"],
  ["原","yuán","original; plain (land)"],
  ["车","chē","vehicle, car"],
  ["白","bái","white; plain; in vain"],
  ["应","yīng / yìng","should; to respond"],
  ["路","lù","road, path"],
  ["期","qī","period of time; to expect"],
  ["叫","jiào","to call, be called; shout"],
  ["死","sǐ","to die; dead; extremely"],
  ["常","cháng","often; common"],
  ["提","tí / dī","to lift, carry; mention"],
  ["感","gǎn","to feel; sense, emotion"],
  ["金","jīn","gold; metal; money"],
  ["何","hé","what, how (classical)"],
  ["更","gèng / gēng","even more; to change"],
  ["反","fǎn","to oppose; reverse; anti-"],
  ["题","tí","topic: 问题 = question, problem"],
  ["建","jiàn","to build, establish"],
  ["度","dù / duó","degree; to spend (time); to measure"],
  ["光","guāng","light; bare; used up"],
  ["非","fēi","not, non-; Africa"],
  ["计","jì","to calculate; plan"],
  ["结","jié / jiē","to tie; knot; to conclude"],
  ["解","jiě","to untie; solve; explain"],
  ["放","fàng","to put, place; release"],
  ["争","zhēng","to contend, fight for"],
  ["让","ràng","to let, allow; yield"],
  ["色","sè","color; appearance"],
  ["王","wáng","king; surname Wang"],
  ["至","zhì","to, until; utmost"],
  ["记","jì","to remember; record"],
  ["特","tè","special, particular"],
  ["战","zhàn","war; to fight"],
  ["决","jué","to decide; definitely"],
  ["各","gè","each, every"],
  ["思","sī","to think, consider"],
  ["完","wán","to finish; complete"],
  ["令","lìng","order, command; to cause"],
  ["队","duì","team; line, queue"],
  ["导","dǎo","to lead, guide"],
  ["论","lùn","theory; to discuss"],
  ["变","biàn","to change, become"],
  ["条","tiáo","strip; measure word for long things"],
  ["收","shōu","to receive, collect"],
  ["证","zhèng","proof; certificate"],
  ["认","rèn","to recognize, admit"],
  ["品","pǐn","product; quality; character"],
  ["量","liàng / liáng","quantity; to measure"],
  ["直","zhí","straight; direct; continuously"],
  ["展","zhǎn","to unfold; exhibit; develop"],
  ["传","chuán / zhuàn","to pass on, spread; biography"],
  ["系","xì / jì","system; department; to tie"],
  ["望","wàng","to gaze at; hope"],
  ["术","shù","technique, method, art"],
  ["视","shì","vision; to look at: 电视 = TV"],
  ["界","jiè","boundary: 世界 = world"],
  ["义","yì","meaning; righteousness; -ism"],
  ["观","guān","to observe; view, outlook"],
  ["士","shì","scholar; soldier; -ist"],
  ["象","xiàng","elephant; appearance, image"],
  ["局","jú","bureau; situation; game (of chess)"],
  ["达","dá","to reach, arrive; express"],
  ["支","zhī","to support; branch; measure word for sticks"],
  ["花","huā","flower; to spend"],
  ["干","gàn / gān","to do; dry"],
  ["官","guān","official, officer; organ (body)"],
  ["音","yīn","sound, tone"],
  ["极","jí","extreme; pole"],
  ["台","tái","platform, stage; measure word for machines"],
  ["且","qiě","moreover: 而且 = furthermore"],
  ["石","shí","stone, rock"],
  ["类","lèi","kind, category"],
  ["集","jí","to gather; collection; episode"],
  ["强","qiáng / qiǎng","strong; to force"],
  ["元","yuán","yuan (money); primary; element"],
  ["星","xīng","star"],
  ["风","fēng","wind; style"],
  ["众","zhòng","crowd; many, numerous"],
  ["流","liú","to flow; current; to spread"],
  ["每","měi","every, each"],
  ["服","fú","clothes; to serve; convinced"],
  ["云","yún","cloud"],
  ["团","tuán","group; ball; to unite"],
  ["区","qū","district, region"],
  ["空","kōng / kòng","empty; sky; free time"],
  ["快","kuài","fast; soon; happy"],
  ["精","jīng","essence; refined; energy"],
  ["需","xū","to need, require"],
  ["转","zhuǎn / zhuàn","to turn; transfer; spin"],
  ["送","sòng","to send; give (gift); see off"],
  ["火","huǒ","fire"],
  ["站","zhàn","to stand; station, stop"],
  ["满","mǎn","full, filled; satisfied"],
  ["容","róng","to contain; appearance: 容易 = easy"],
  ["究","jiū","to investigate: 研究 = research"],
  ["早","zǎo","early; morning"],
  ["消","xiāo","to disappear, eliminate: 消息 = news"],
  ["亲","qīn","parent; relative; intimate; to kiss"],
  ["写","xiě","to write"],
  ["断","duàn","to break, cut off; to judge"],
  ["深","shēn","deep; profound"],
  ["越","yuè","to exceed; the more...; Vietnam"],
  ["希","xī","to hope: 希望 = hope"],
  ["察","chá","to examine: 警察 = police"],
  ["备","bèi","to prepare; equipment"],
  ["半","bàn","half"],
  ["办","bàn","to handle, do, manage"],
  ["青","qīng","green-blue; young"],
  ["换","huàn","to exchange, change"],
  ["排","pái","to arrange; row, line"],
  ["据","jù","according to; evidence"],
  ["言","yán","speech, words, language"],
  ["千","qiān","thousand"],
  ["语","yǔ","language, speech"],
  ["六","liù","six"],
  ["首","shǒu","head; first; measure word for songs"],
  ["求","qiú","to seek, request, beg"],
  ["价","jià","price, value"],
  ["增","zēng","to increase, add"],
  ["必","bì","must, necessarily"],
  ["存","cún","to exist; store, save"],
  ["周","zhōu","week; circumference; surname Zhou"],
  ["城","chéng","city; city wall"],
  ["试","shì","to try; test, exam"],
  ["帮","bāng","to help; gang"],
  ["影","yǐng","shadow; image: 电影 = movie"],
  ["落","luò / là","to fall, drop; to leave behind"],
  ["商","shāng","commerce, business; to discuss"],
  ["请","qǐng","please; to invite, request"],
  ["单","dān","single; list, bill; simple"],
  ["木","mù","tree, wood"],
  ["布","bù","cloth; to spread, announce"],
  ["算","suàn","to calculate; count as; plan"],
  ["男","nán","man, male"],
  ["词","cí","word, term"],
  ["曾","céng / zēng","once, formerly; great- (kin)"],
  ["段","duàn","section, paragraph; period"],
  ["联","lián","to join, connect, unite"],
  ["河","hé","river"],
  ["织","zhī","to weave: 组织 = organization"],
  ["组","zǔ","group; to form, organize"],
  ["属","shǔ","to belong to; category"],
  ["严","yán","strict; severe"],
  ["领","lǐng","to lead; collar; to receive"],
  ["微","wēi","tiny, micro-; slight"],
  ["突","tū","to burst: 突然 = suddenly"],
  ["双","shuāng","pair; double, both"],
  ["例","lì","example; case; rule"],
  ["承","chéng","to bear, undertake; inherit"],
  ["冷","lěng","cold"],
  ["热","rè","hot; heat; popular"],
  ["血","xuè / xiě","blood"],
  ["兵","bīng","soldier; weapons"],
  ["校","xiào / jiào","school; to check, proofread"],
  ["灯","dēng","lamp, light"],
  ["香","xiāng","fragrant; incense; 香港 = Hong Kong"],
  ["药","yào","medicine, drug"],
  ["树","shù","tree"],
  ["鱼","yú","fish"],
  ["鸟","niǎo","bird"],
  ["雨","yǔ","rain"],
  ["雪","xuě","snow"],
  ["七","qī","seven"],
  ["八","bā","eight"],
  ["百","bǎi","hundred"],
  ["零","líng","zero"],
  ["吃","chī","to eat"],
  ["喝","hē","to drink"],
  ["睡","shuì","to sleep"],
  ["买","mǎi","to buy"],
  ["卖","mài","to sell"],
  ["钱","qián","money"],
  ["妈","mā","mom, mother"],
  ["爸","bà","dad, father"],
  ["哥","gē","older brother"],
  ["姐","jiě","older sister"],
  ["弟","dì","younger brother"],
  ["妹","mèi","younger sister"],
  ["猫","māo","cat"],
  ["狗","gǒu","dog"],
  ["茶","chá","tea"],
  ["米","mǐ","rice (uncooked); meter"],
  ["饭","fàn","cooked rice; meal"],
  ["菜","cài","vegetable; dish (food)"],
  ["肉","ròu","meat, flesh"],
  ["蛋","dàn","egg"],
  ["跑","pǎo","to run"],
  ["跳","tiào","to jump"],
  ["坐","zuò","to sit; to travel by"],
  ["读","dú","to read; study"],
  ["唱","chàng","to sing"],
  ["歌","gē","song"],
  ["玩","wán","to play; have fun"],
  ["哭","kū","to cry, weep"],
  ["爱","ài","to love; love"],
  ["窗","chuāng","window"],
  ["床","chuáng","bed"],
  ["房","fáng","house; room"],
  ["屋","wū","room; house"],
  ["桌","zhuō","table, desk"],
  ["椅","yǐ","chair"],
  ["飞","fēi","to fly"],
  ["船","chuán","boat, ship"],
  ["票","piào","ticket"],
  ["店","diàn","shop, store"],
  ["街","jiē","street"],
  ["村","cūn","village"],
  ["朋","péng","friend: 朋友"],
  ["友","yǒu","friend; friendly"],
  ["字","zì","character, word; letter"],
  ["纸","zhǐ","paper"],
  ["笔","bǐ","pen, brush; stroke"],
  ["画","huà","to draw; painting"],
  ["图","tú","picture, diagram, map"],
  ["红","hóng","red; popular"],
  ["黄","huáng","yellow; surname Huang"],
  ["蓝","lán","blue"],
  ["绿","lǜ","green"],
  ["黑","hēi","black; dark"],
  ["左","zuǒ","left (side)"],
  ["右","yòu","right (side)"],
  ["南","nán","south"],
  ["春","chūn","spring (season)"],
  ["夏","xià","summer"],
  ["秋","qiū","autumn, fall"],
  ["冬","dōng","winter"],
  ["晚","wǎn","evening, night; late"],
  ["夜","yè","night"],
  ["午","wǔ","noon"],
  ["昨","zuó","yesterday: 昨天"],
  ["今","jīn","now, today: 今天"],
  ["脸","liǎn","face"],
  ["嘴","zuǐ","mouth"],
  ["耳","ěr","ear"],
  ["鼻","bí","nose"],
  ["脚","jiǎo","foot, leg"],
  ["腿","tuǐ","leg"],
  ["牙","yá","tooth"],
  ["骨","gǔ","bone"],
  ["皮","pí","skin, leather"],
  ["毛","máo","hair, fur; 10 cents"],
  ["牛","niú","cow, ox"],
  ["羊","yáng","sheep, goat"],
  ["猪","zhū","pig"],
  ["鸡","jī","chicken"],
  ["虎","hǔ","tiger"],
  ["龙","lóng","dragon"],
  ["蛇","shé","snake"],
  ["兔","tù","rabbit"],
  ["熊","xióng","bear"],
  ["果","guǒ","fruit; result"],
  ["瓜","guā","melon, gourd"],
  ["豆","dòu","bean"],
  ["糖","táng","sugar; candy"],
  ["盐","yán","salt"],
  ["油","yóu","oil"],
  ["汤","tāng","soup"],
  ["酒","jiǔ","alcohol, wine"],
  ["杯","bēi","cup, glass"],
  ["碗","wǎn","bowl"],
  ["刀","dāo","knife"],
  ["伞","sǎn","umbrella"],
  ["衣","yī","clothes"],
  ["裤","kù","trousers, pants"],
  ["鞋","xié","shoe"],
  ["帽","mào","hat"],
  ["穿","chuān","to wear; pierce through"],
  ["洗","xǐ","to wash"],
  ["澡","zǎo","bath: 洗澡 = to bathe"],
  ["病","bìng","illness; sick"],
  ["医","yī","medicine; doctor"],
  ["院","yuàn","courtyard; institute: 医院 = hospital"],
  ["疼","téng","to hurt, ache; to dote on"],
  ["累","lèi / lěi","tired; to accumulate"],
  ["忙","máng","busy"],
  ["慢","màn","slow"],
  ["远","yuǎn","far, distant"],
  ["近","jìn","near, close"],
  ["旧","jiù","old (things), worn"],
  ["脏","zāng / zàng","dirty; internal organ"],
  ["净","jìng","clean; only"],
  ["胖","pàng","fat, plump"],
  ["瘦","shòu","thin, skinny; lean"],
  ["贵","guì","expensive; noble"],
  ["谁","shéi","who"],
  ["吗","ma","yes/no question particle"],
  ["呢","ne","question/softening particle"],
  ["吧","ba","suggestion particle (let's...)"],
  ["啊","a / ā","exclamation particle"],
  ["哪","nǎ","which; where (哪儿)"],
  ["怎","zěn","how: 怎么"],
  ["号","hào","number; date; size"],
  ["岁","suì","years of age"],
  ["块","kuài","piece, lump; yuan (colloquial)"],
  ["运","yùn","to transport; luck; motion"],
  ["球","qiú","ball, sphere"],
  ["游","yóu","to swim; to tour"],
  ["泳","yǒng","to swim: 游泳"],
  ["休","xiū","to rest: 休息"],
  ["息","xī","to rest; breath; interest (money)"],
  ["班","bān","class; work shift; scheduled trip"],
  ["课","kè","class, lesson"],
  ["考","kǎo","to test, examine"],
  ["答","dá / dā","to answer, reply"],
  ["错","cuò","wrong; mistake"],
  ["懂","dǒng","to understand"],
  ["忘","wàng","to forget"],
  ["找","zhǎo","to look for; give change"],
  ["丢","diū","to lose, throw away"],
  ["拿","ná","to take, hold"],
  ["借","jiè","to borrow, lend"],
  ["推","tuī","to push"],
  ["拉","lā","to pull"],
  ["抱","bào","to hug, embrace"],
  ["握","wò","to grasp, hold: 握手 = shake hands"],
  ["指","zhǐ","finger; to point"],
  ["接","jiē","to receive; pick up; connect"],
  ["扔","rēng","to throw"],
  ["搬","bān","to move (things); carry"],
  ["带","dài","to bring; belt; band"],
  ["该","gāi","should, ought to"],
  ["愿","yuàn","to wish, be willing"],
  ["敢","gǎn","to dare"],
  ["怕","pà","to fear, be afraid"],
  ["惊","jīng","to startle, surprise"],
  ["急","jí","urgent; anxious"],
  ["静","jìng","quiet, still"],
  ["闹","nào","noisy; to make a fuss"],
  ["吵","chǎo","noisy; to quarrel"],
  ["困","kùn","sleepy; trapped; difficulty"],
  ["饿","è","hungry"],
  ["渴","kě","thirsty"],
  ["痛","tòng","pain, ache"],
  ["舒","shū","comfortable: 舒服"],
  ["脑","nǎo","brain: 电脑 = computer"],
  ["网","wǎng","net; internet"],
  ["线","xiàn","thread, line, wire"],
  ["桥","qiáo","bridge"],
  ["楼","lóu","building; floor, story"],
  ["层","céng","layer; floor"],
  ["墙","qiáng","wall"],
  ["土","tǔ","soil, earth"],
  ["田","tián","field, farmland"],
  ["林","lín","forest, woods"],
  ["草","cǎo","grass"],
  ["叶","yè","leaf"],
  ["根","gēn","root; measure word for long thin things"],
  ["湖","hú","lake"],
  ["江","jiāng","(large) river"],
  ["洋","yáng","ocean; foreign"],
  ["岛","dǎo","island"],
  ["沙","shā","sand"],
  ["冰","bīng","ice"],
  ["温","wēn","warm; temperature"],
  ["凉","liáng","cool, cold"],
  ["晴","qíng","sunny, clear"],
  ["阴","yīn","cloudy; yin; shade"],
  ["阳","yáng","sun; yang: 太阳 = sun"],
  ["季","jì","season"],
  ["节","jié","festival: 节日; joint, section"],
  ["假","jiǎ / jià","fake; vacation"],
  ["礼","lǐ","gift; courtesy, ritual"],
  ["物","wù","thing, object"],
  ["食","shí","food; to eat"],
  ["味","wèi","taste, flavor; smell"],
  ["甜","tián","sweet"],
  ["苦","kǔ","bitter; hardship"],
  ["酸","suān","sour; acid"],
  ["辣","là","spicy, hot"],
  ["咸","xián","salty"],
  ["久","jiǔ","long time"],
  ["刚","gāng","just (now); firm"],
  ["共","gòng","together; altogether"],
  ["另","lìng","other, another"],
  ["份","fèn","portion, share; copy"],
  ["整","zhěng","whole; exactly; to fix"],
  ["约","yuē","appointment; approximately"],
  ["差","chà / chā","to differ; poor (quality); short of"],
  ["够","gòu","enough"],
  ["剩","shèng","to remain, be left over"],
  ["超","chāo","to exceed; super-"],
  ["低","dī","low"],
  ["矮","ǎi","short (height)"],
  ["粗","cū","thick, coarse"],
  ["细","xì","thin, fine; careful"],
  ["宽","kuān","wide; lenient"],
  ["窄","zhǎi","narrow"],
  ["圆","yuán","round; circle"],
  ["弯","wān","curved, bent"],
  ["软","ruǎn","soft"],
  ["硬","yìng","hard, stiff"],
  ["轻","qīng","light (weight); gentle"],
  ["湿","shī","wet"],
  ["亮","liàng","bright; to shine"],
  ["暗","àn","dark, dim"],
  ["危","wēi","danger: 危险"],
  ["险","xiǎn","dangerous; risk"],
  ["奇","qí","strange; odd"],
  ["怪","guài","strange; to blame"],
  ["丑","chǒu","ugly"],
  ["帅","shuài","handsome; commander"],
  ["聪","cōng","clever: 聪明 = smart"],
  ["笨","bèn","stupid, clumsy"],
  ["穷","qióng","poor"],
  ["富","fù","rich, wealthy"],
  ["弱","ruò","weak"],
  ["胜","shèng","to win; victory"],
  ["败","bài","to lose, be defeated"],
  ["赢","yíng","to win"],
  ["输","shū","to lose; to transport"],
  ["始","shǐ","to begin: 开始 = start"],
  ["终","zhōng","end; finally"],
  ["停","tíng","to stop; park"],
  ["继","jì","to continue: 继续"],
  ["续","xù","to continue; renew"],
  ["选","xuǎn","to choose, elect"],
  ["式","shì","style, type; formula"],
  ["规","guī","rule, regulation"],
  ["制","zhì","system; to make, control"],
  ["造","zào","to make, build, create"],
  ["修","xiū","to repair; build; study"],
  ["装","zhuāng","to install; pretend; clothing"],
  ["设","shè","to set up; design (设计)"],
  ["查","chá","to check, look up"],
  ["验","yàn","to test, verify: 经验 = experience"],
  ["研","yán","to research, grind"],
  ["科","kē","science; department, branch"],
  ["技","jì","skill, technique: 科技 = technology"],
  ["器","qì","device, utensil"],
  ["具","jù","tool; to possess"],
  ["料","liào","material; to expect"],
  ["源","yuán","source, origin"],
  ["质","zhì","quality; substance"],
  ["境","jìng","border; situation: 环境 = environment"],
  ["环","huán","ring; to surround"],
  ["保","bǎo","to protect, keep"],
  ["护","hù","to protect: 保护"],
  ["养","yǎng","to raise, nurture"],
  ["育","yù","to educate, raise: 教育 = education"],
  ["健","jiàn","healthy, strong: 健康"],
  ["康","kāng","health, well-being"],
  ["般","bān","sort, kind: 一般 = ordinary"],
  ["级","jí","level, grade, rank"],
  ["初","chū","beginning, first"],
  ["末","mò","end, tip: 周末 = weekend"],
  ["史","shǐ","history"],
  ["古","gǔ","ancient, old"],
  ["典","diǎn","canon, standard: 字典 = dictionary"],
  ["诗","shī","poem, poetry"],
  ["故","gù","reason; old: 故事 = story"],
  ["讲","jiǎng","to speak, tell, explain"],
  ["谈","tán","to talk, discuss"],
  ["聊","liáo","to chat"],
  ["议","yì","to discuss: 会议 = meeting"],
  ["念","niàn","to read aloud; miss (someone); idea"],
  ["梦","mèng","dream"],
  ["醒","xǐng","to wake up"],
  ["睛","jīng","eyeball: 眼睛 = eye"],
  ["泪","lèi","tear (crying)"],
  ["汗","hàn","sweat"],
  ["响","xiǎng","to sound; loud; echo"],
  ["乐","lè / yuè","happy; music"],
  ["舞","wǔ","dance; to dance"],
  ["戏","xì","play, drama; to play"],
  ["剧","jù","drama, play; severe"],
  ["演","yǎn","to perform, act"],
  ["赛","sài","competition, match"],
  ["奖","jiǎng","prize, award"],
  ["努","nǔ","to exert: 努力 = to strive"],
  ["功","gōng","merit, achievement: 成功 = success"],
  ["志","zhì","will, aspiration"],
  ["永","yǒng","forever, eternal"],
  ["恒","héng","constant, lasting"],
  ["福","fú","good fortune, blessing"],
  ["喜","xǐ","to like; joy: 喜欢 = to like"],
  ["欢","huān","joyful, happy"],
  ["悲","bēi","sad, sorrowful"],
  ["伤","shāng","wound, injury; to hurt"],
  ["恨","hèn","to hate; regret"],
  ["怒","nù","anger, fury"],
  ["烦","fán","annoyed; to bother"],
  ["愁","chóu","to worry; sorrow"],
  ["羞","xiū","shy, ashamed"],
  ["骄","jiāo","proud, arrogant: 骄傲"],
  ["谢","xiè","to thank: 谢谢"],
  ["祝","zhù","to wish (someone well)"],
  ["贺","hè","to congratulate: 祝贺"],
  ["迎","yíng","to welcome: 欢迎"],
  ["客","kè","guest, customer"],
  ["席","xí","seat; banquet; 主席 = chairman"],
];
